/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        StandardCalculator calc = new StandardCalculator();
        calc.add(Double.MAX_VALUE, Double.MAX_VALUE);
        

LogicCalculator calc1 = new LogicCalculator();

calc1.AND(8, 6);

calc1.printResult();

        


    //     System.out.println("Starting QCalc..");
    //    StandardCalculator calc = new StandardCalculator();
    // //    calc.add(1.5, 2.5);
    //    calc.divide(10.5, 2.5);
       System.out.println(calc.getResult());

    //     // System.out.println(new App().getGreeting());
    }
}
